### ISSUE TITLE
Switch to a Jackson for Json

### ISSUE THREAD

**Issue by re-thc** [arangodb/java-velocypack#8]
Hi, can the json implementation be switched to Jackson? Jackson is standardized and used across the board in most projects. json-simple creates an extra dependency for us. Also as it's more heavily tested any issues, such as security are better looked after.

As an added bonus Jackon is faster. If size is an issue please look at jackson-jr.

Thanks!

**Comment by mvollmary** [comment]
Hi @hc-codersatlas,
I started this project long time ago (see [here](https://github.com/arangodb/jackson-dataformat-velocypack)). But, at the moment, I do not have the time to get it done. And - as far as I remember - I was kind of stuck because `jackson-databind` requires Java 7 and we wanted to stick to 6 with our driver. I try to discuss this topic internally since months with no progress so far. I will gladly keep you informed.

best
Mark

**Comment by re-thc** [comment]
Thanks for the response. Hopefully we can move to Jackson. Looking forward to adopt Arangodb for our use case.

**Comment by mvollmary** [comment]
@hc-codersatlas I replaced json-simple with jackson right now. The change will be included in the upcoming driver release next week.

**Comment by re-thc** [comment]
Great, thanks.
